server:
  port: 8990

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev, mysql}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:localhost:8848} # Nacos 服务器地址
        namespace: dev
        group: CLOUD_DEV_GROUP
    gateway:
      routes:
        - id: base_route # 路由 id,需要唯一
          uri: lb://base # 路由的目标地址 lb：负载均衡。双斜线后面的是服务名
#          uri: https://example.org # 路由的目标地址（固定地址）
          predicates: # 路由断言，判断请求是否符合路由规则的条件
            - Path=/base/**
        - id: security-route
          uri: lb://security
          predicates:
            - Path=/security/**
#            - Cookie=mycookie,mycookievalue
#            -
  application:
    name: gateway
